export { default as AutoForm } from '@@/components/ui/auto-form/AutoForm.vue'
export { default as AutoFormField } from '@@/components/ui/auto-form/AutoFormField.vue'

export { default as AutoFormFieldArray } from '@@/components/ui/auto-form/AutoFormFieldArray.vue'
export { default as AutoFormFieldBoolean } from '@@/components/ui/auto-form/AutoFormFieldBoolean.vue'
export { default as AutoFormFieldDate } from '@@/components/ui/auto-form/AutoFormFieldDate.vue'

export { default as AutoFormFieldEnum } from '@@/components/ui/auto-form/AutoFormFieldEnum.vue'
export { default as AutoFormFieldFile } from '@@/components/ui/auto-form/AutoFormFieldFile.vue'
export { default as AutoFormFieldInput } from '@@/components/ui/auto-form/AutoFormFieldInput.vue'
export { default as AutoFormFieldNumber } from '@@/components/ui/auto-form/AutoFormFieldNumber.vue'
export { default as AutoFormFieldObject } from '@@/components/ui/auto-form/AutoFormFieldObject.vue'
export { default as AutoFormLabel } from '@@/components/ui/auto-form/AutoFormLabel.vue'
export type { Config, ConfigItem, FieldProps } from './interface'
export { getBaseSchema, getBaseType, getObjectFormSchema } from './utils'
